<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rkt</string>
	</array>
	<key>name</key>
	<string>Racket</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()(define)\s+([a-zA-Z0-9_\-?\+^]+)\s*</string>
			<key>name</key>
			<string>meta.variable.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()(define)\s+(\()([a-zA-Z0-9_\-?\+^]+)\s*</string>
			<key>name</key>
			<string>meta.function.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.type.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()(define-syntax)\s+(\()([a-zA-Z0-9_\-?\+^]+)\s*</string>
			<key>name</key>
			<string>meta.class.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\))</string>
			<key>name</key>
			<string>entity.name.variable.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(if|lambda|cond|define|type-case|let|letrec|let!|\#lang|require|test|else|first|rest|define-type|define-type-alias|define-struct|not|local|error|lang|module|submod|dynamic-place|future|touch|for/list|for|match|define-syntax|syntax-case|define-values|values|struct|thread|channel-put|channel-get|sync|handle-evt|λ|apply|map|list|cons|car|cdr|append|define-runtime-path|set\!|provide|prefix-in|for-syntax|only-in|for-each|for/fold|dynamic-require|place-channel-get|place-channel-put|printf|place-wait|thread-wait|or|and|not|struct-out|contract-out|define-syntax-rule|begin|begin0|parameterize|in-list|for/vector|let\*|unless|when|null\?|hash-set\!|hash-ref|hash-keys|hash-update\!|length|flatten|filter|make-hash|case|send|new|format)[\s\)]</string>
			<key>name</key>
			<string>meta.keywords.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|empty|cons)[\s\)]</string>
			<key>name</key>
			<string>constant.language.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0|([1-9][0-9_]*))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#(t|f)</string>
			<key>name</key>
			<string>constant.numeric.integer.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#:([a-zA-Z0-9_\-?\+^]+)*</string>
			<key>name</key>
			<string>constant.numeric.integer.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'([a-zA-Z0-9_\-?\+^]+)*</string>
			<key>name</key>
			<string>constant.numeric.integer.source.racket</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.documentation.source.racket</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.racket</string>
	<key>uuid</key>
	<string>afda310a-1b2e-4b97-a0f7-13819a0ee21f</string>
</dict>
</plist>
